#source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

target 'LYToolsKit_Example' do
  pod 'LYToolsKit', :path => '../'

  target 'LYToolsKit_Tests' do
    inherit! :search_paths

  end
end
